#!/data/data/com.termux/files/usr/bin/sh
pkg remove termux-display-nightly -y 2>&1 >/dev/tty
pkg remove termux-x11-nightly -y 2>&1 >/dev/tty
echo "Upgrade..." 2>&1 >/dev/tty
yes | pkg up 2>&1 >/dev/tty
yes | apt install -f -y 2>&1 >/dev/tty
yes | pkg i x11-repo 2>&1 >/dev/tty
cd ~
echo "Install termux-x11-nightly..." 2>&1 >/dev/tty
yes | apt install ./termux-x11-nightly-1.03.10-0-all.deb 2>&1 >/dev/tty
yes | apt autoremove 2>&1 >/dev/tty
yes | apt install xwayland 2>&1 >/dev/tty
ehco "Done" 2>&1 >/dev/tty
# rm -rf $0